# Generated by Django 4.2.7 on 2023-11-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
