# Generated by Django 4.2.10 on 2024-02-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_websiteuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='avatars'),
        ),
    ]
