# Generated by Django 4.2.7 on 2023-11-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_websiteuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
