# Generated by Django 4.2.10 on 2024-02-07 13:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_websiteuser_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='friends',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
