# Generated by Django 4.2.10 on 2024-02-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_friendship_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
