# Generated by Django 4.2.10 on 2024-02-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_calendar', '0002_alter_event_organizer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
