# Generated by Django 4.2.10 on 2024-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='accepted',
            field=models.CharField(choices=[('WT', 'Waiting'), ('ACK', 'Accepted'), ('NACK', 'Rejected')], default='WT', max_length=5),
        ),
    ]
